buildscript {
    repositories {
        google()
        mavenCentral()
        maven { url "https://repo.maven.apache.org/maven2" }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.10.1'
    }
}
apply plugin: 'com.android.application'

repositories {
        mavenCentral()
        maven { url "https://maven.google.com" }
}

android {
    namespace 'com.goodecho.app'
    compileSdk 34

    defaultConfig{
        applicationId "com.goodecho.app"
        minSdk 30
        targetSdk 34
        versionCode 15
        versionName "2.0.0"
    }

    buildTypes {
        release {
            minifyEnabled true
            proguardFile file('proguard.cfg')
            proguardFile getDefaultProguardFile('proguard-android-optimize.txt')
        }

        debug {
        }
    }
    lint {
        abortOnError false
    }
    buildFeatures {
        buildConfig false
    }

}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'androidx.recyclerview:recyclerview:1.3.2'
    implementation 'io.github.jaredmdobson:concentus:1.0.2'
}
